### ISSUE TITLE
Warning: Invalid argument supplied for foreach() in morfy\Blocks.php on line 43

### ISSUE THREAD

**Issue by ebookcode** [morfy-cms/morfy.org#2]
Detail: when I tried every link, I got the message:

Warning: Invalid argument supplied for foreach() in C:\PortableProg\UwAmp\www\cms\flatfile-cms\morfy-2.0.2-example-morfy.org\morfy\Blocks.php on line 43

https://github.com/morfy-cms/morfy.org/blob/master/morfy/Blocks.php#L43

I've tried to debug at: C:\PortableProg\UwAmp\www\cms\flatfile-cms\morfy-2.0.2-example-morfy.org\morfy\Blocks.php

I change the line 41: $blocks = File::scan(STORAGE_PATH . '/blocks', 'md');var_dump(STORAGE_PATH . '/blocks');die;

and see:
string 'C:/PortableProg/UwAmp/www/cms/flatfile-cms/morfy-2.0.2-example-morfy.org/storage/blocks' (length=87)

**Comment by Awilum** [comment]
Fixed
